USE [master]
GO

/****** Object:  Database [bus_booking]    Script Date: 05.01.2026 10:56:51 ******/
CREATE DATABASE [bus_booking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bus_booking', FILENAME = N'/var/opt/mssql/data/bus_booking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bus_booking_log', FILENAME = N'/var/opt/mssql/data/bus_booking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bus_booking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bus_booking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bus_booking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bus_booking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bus_booking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bus_booking] SET ARITHABORT OFF 
GO

ALTER DATABASE [bus_booking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bus_booking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bus_booking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bus_booking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bus_booking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bus_booking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bus_booking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bus_booking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bus_booking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bus_booking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bus_booking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bus_booking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bus_booking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bus_booking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bus_booking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bus_booking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bus_booking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bus_booking] SET RECOVERY FULL 
GO

ALTER DATABASE [bus_booking] SET  MULTI_USER 
GO

ALTER DATABASE [bus_booking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bus_booking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bus_booking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bus_booking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bus_booking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bus_booking] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [bus_booking] SET QUERY_STORE = ON
GO

ALTER DATABASE [bus_booking] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [bus_booking] SET  READ_WRITE 
GO

